function [ J ] = So_Jacobian_for_Cal(  Theta1, Theta2, Theta3, Theta4, Theta5, Theta6, Theta7, a2, a3, a4 )
%SO_JACOBIAN_FOR_CAL Summary of this function goes here
%   Detailed explanation goes here


% t1 = So_Theta_to_Rad(Theta1);
% t2 = So_Theta_to_Rad(Theta2);
% t3 = So_Theta_to_Rad(Theta3);
% t4 = So_Theta_to_Rad(Theta4);
% t5 = So_Theta_to_Rad(Theta5);
% t6 = So_Theta_to_Rad(Theta6);

t1 = Theta1;
t2 = Theta2;
t3 = Theta3;
t4 = Theta4;
t5 = Theta5;
t6 = Theta6;
t7 = Theta7;

J = [ 3*sin(t1)*sin(t2) + cos(t6)*(sin(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) + cos(t4)*sin(t1)*sin(t2)) + sin(t6)*(cos(t5)*(cos(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) - sin(t1)*sin(t2)*sin(t4)) + sin(t5)*(cos(t1)*cos(t3) - cos(t2)*sin(t1)*sin(t3))) + 3*sin(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) + 3*cos(t4)*sin(t1)*sin(t2),                -cos(t1)*(3*cos(t2) + 3*cos(t2)*cos(t4) - sin(t6)*(cos(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) - sin(t2)*sin(t3)*sin(t5)) + cos(t6)*(cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4)) - 3*cos(t3)*sin(t2)*sin(t4)), 3*cos(t3)*sin(t1)*sin(t4) + 3*cos(t1)*cos(t2)*sin(t3)*sin(t4) + cos(t3)*cos(t6)*sin(t1)*sin(t4) - sin(t1)*sin(t3)*sin(t5)*sin(t6) + cos(t1)*cos(t2)*cos(t6)*sin(t3)*sin(t4) + cos(t1)*cos(t2)*cos(t3)*sin(t5)*sin(t6) + cos(t3)*cos(t4)*cos(t5)*sin(t1)*sin(t6) + cos(t1)*cos(t2)*cos(t4)*cos(t5)*sin(t3)*sin(t6), sin(t2)*sin(t3)*(cos(t6)*(sin(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) + cos(t4)*sin(t1)*sin(t2)) + sin(t6)*(cos(t5)*(cos(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) - sin(t1)*sin(t2)*sin(t4)) + sin(t5)*(cos(t1)*cos(t3) - cos(t2)*sin(t1)*sin(t3))) + 3*sin(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) + 3*cos(t4)*sin(t1)*sin(t2)) - (cos(t1)*cos(t3) - cos(t2)*sin(t1)*sin(t3))*(3*cos(t2)*cos(t4) - sin(t6)*(cos(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) - sin(t2)*sin(t3)*sin(t5)) + cos(t6)*(cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4)) - 3*cos(t3)*sin(t2)*sin(t4)), sin(t6)*(cos(t3)*cos(t5)*sin(t1) + cos(t1)*cos(t2)*cos(t5)*sin(t3) - cos(t1)*sin(t2)*sin(t4)*sin(t5) - cos(t4)*sin(t1)*sin(t3)*sin(t5) + cos(t1)*cos(t2)*cos(t3)*cos(t4)*sin(t5)), (sin(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) + cos(t5)*sin(t2)*sin(t3))*(cos(t6)*(sin(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) + cos(t4)*sin(t1)*sin(t2)) + sin(t6)*(cos(t5)*(cos(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) - sin(t1)*sin(t2)*sin(t4)) + sin(t5)*(cos(t1)*cos(t3) - cos(t2)*sin(t1)*sin(t3)))) - (sin(t5)*(cos(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) - sin(t1)*sin(t2)*sin(t4)) - cos(t5)*(cos(t1)*cos(t3) - cos(t2)*sin(t1)*sin(t3)))*(sin(t6)*(cos(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) - sin(t2)*sin(t3)*sin(t5)) - cos(t6)*(cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4))),                                                                                                                                                                                                                                                   0;
      cos(t6)*(sin(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) - cos(t1)*cos(t4)*sin(t2)) - 3*cos(t1)*sin(t2) + sin(t6)*(cos(t5)*(cos(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) + cos(t1)*sin(t2)*sin(t4)) + sin(t5)*(cos(t3)*sin(t1) + cos(t1)*cos(t2)*sin(t3))) + 3*sin(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) - 3*cos(t1)*cos(t4)*sin(t2),                -sin(t1)*(3*cos(t2) + 3*cos(t2)*cos(t4) - sin(t6)*(cos(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) - sin(t2)*sin(t3)*sin(t5)) + cos(t6)*(cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4)) - 3*cos(t3)*sin(t2)*sin(t4)), 3*cos(t2)*sin(t1)*sin(t3)*sin(t4) - cos(t1)*cos(t3)*cos(t6)*sin(t4) - 3*cos(t1)*cos(t3)*sin(t4) + cos(t1)*sin(t3)*sin(t5)*sin(t6) - cos(t1)*cos(t3)*cos(t4)*cos(t5)*sin(t6) + cos(t2)*cos(t6)*sin(t1)*sin(t3)*sin(t4) + cos(t2)*cos(t3)*sin(t1)*sin(t5)*sin(t6) + cos(t2)*cos(t4)*cos(t5)*sin(t1)*sin(t3)*sin(t6), sin(t2)*sin(t3)*(cos(t6)*(sin(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) - cos(t1)*cos(t4)*sin(t2)) + sin(t6)*(cos(t5)*(cos(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) + cos(t1)*sin(t2)*sin(t4)) + sin(t5)*(cos(t3)*sin(t1) + cos(t1)*cos(t2)*sin(t3))) + 3*sin(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) - 3*cos(t1)*cos(t4)*sin(t2)) - (cos(t3)*sin(t1) + cos(t1)*cos(t2)*sin(t3))*(3*cos(t2)*cos(t4) - sin(t6)*(cos(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) - sin(t2)*sin(t3)*sin(t5)) + cos(t6)*(cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4)) - 3*cos(t3)*sin(t2)*sin(t4)), sin(t6)*(cos(t2)*cos(t5)*sin(t1)*sin(t3) - cos(t1)*cos(t3)*cos(t5) + cos(t1)*cos(t4)*sin(t3)*sin(t5) - sin(t1)*sin(t2)*sin(t4)*sin(t5) + cos(t2)*cos(t3)*cos(t4)*sin(t1)*sin(t5)), (sin(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) + cos(t5)*sin(t2)*sin(t3))*(cos(t6)*(sin(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) - cos(t1)*cos(t4)*sin(t2)) + sin(t6)*(cos(t5)*(cos(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) + cos(t1)*sin(t2)*sin(t4)) + sin(t5)*(cos(t3)*sin(t1) + cos(t1)*cos(t2)*sin(t3)))) - (sin(t5)*(cos(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) + cos(t1)*sin(t2)*sin(t4)) - cos(t5)*(cos(t3)*sin(t1) + cos(t1)*cos(t2)*sin(t3)))*(sin(t6)*(cos(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) - sin(t2)*sin(t3)*sin(t5)) - cos(t6)*(cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4))),                                                                                                                                                                                                                                                   0;
                                                                                                                                                                                                                                                                                                                                                              0, cos(t2)*sin(t3)*sin(t5)*sin(t6) - 3*cos(t4)*sin(t2) - 3*cos(t2)*cos(t3)*sin(t4) - cos(t4)*cos(t6)*sin(t2) - cos(t2)*cos(t3)*cos(t6)*sin(t4) - 3*sin(t2) + cos(t5)*sin(t2)*sin(t4)*sin(t6) - cos(t2)*cos(t3)*cos(t4)*cos(t5)*sin(t6),                                                                                                                                                                                                 sin(t2)*(3*sin(t3)*sin(t4) + cos(t6)*sin(t3)*sin(t4) + cos(t3)*sin(t5)*sin(t6) + cos(t4)*cos(t5)*sin(t3)*sin(t6)),                                                                                                                                                                                                                                                                                                                                                                                                                 cos(t3)*cos(t5)*sin(t2)*sin(t4)*sin(t6) - 3*cos(t3)*cos(t4)*sin(t2) - cos(t2)*cos(t6)*sin(t4) - cos(t3)*cos(t4)*cos(t6)*sin(t2) - cos(t2)*cos(t4)*cos(t5)*sin(t6) - 3*cos(t2)*sin(t4),                                                                                     sin(t6)*(cos(t5)*sin(t2)*sin(t3) + cos(t2)*sin(t4)*sin(t5) + cos(t3)*cos(t4)*sin(t2)*sin(t5)),                                                                                                                                                                                                                                                                                                                                                                                                                                                               cos(t3)*sin(t2)*sin(t4)*sin(t6) - cos(t2)*cos(t5)*cos(t6)*sin(t4) - cos(t2)*cos(t4)*sin(t6) + cos(t6)*sin(t2)*sin(t3)*sin(t5) - cos(t3)*cos(t4)*cos(t5)*cos(t6)*sin(t2),                                                                                                                                                                                                                                                   0;
                                                                                                                                                                                                                                                                                                                                                              0,                                                                                                                                                                                                                             sin(t1),                                                                                                                                                                                                                                                                                                  -cos(t1)*sin(t2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cos(t3)*sin(t1) + cos(t1)*cos(t2)*sin(t3),                                                                                                     sin(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) - cos(t1)*cos(t4)*sin(t2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         cos(t5)*(cos(t3)*sin(t1) + cos(t1)*cos(t2)*sin(t3)) - sin(t5)*(cos(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) + cos(t1)*sin(t2)*sin(t4)),   cos(t6)*(sin(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) - cos(t1)*cos(t4)*sin(t2)) + sin(t6)*(cos(t5)*(cos(t4)*(sin(t1)*sin(t3) - cos(t1)*cos(t2)*cos(t3)) + cos(t1)*sin(t2)*sin(t4)) + sin(t5)*(cos(t3)*sin(t1) + cos(t1)*cos(t2)*sin(t3)));
                                                                                                                                                                                                                                                                                                                                                              0,                                                                                                                                                                                                                            -cos(t1),                                                                                                                                                                                                                                                                                                  -sin(t1)*sin(t2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cos(t2)*sin(t1)*sin(t3) - cos(t1)*cos(t3),                                                                                                   - sin(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) - cos(t4)*sin(t1)*sin(t2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         sin(t5)*(cos(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) - sin(t1)*sin(t2)*sin(t4)) - cos(t5)*(cos(t1)*cos(t3) - cos(t2)*sin(t1)*sin(t3)), - cos(t6)*(sin(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) + cos(t4)*sin(t1)*sin(t2)) - sin(t6)*(cos(t5)*(cos(t4)*(cos(t1)*sin(t3) + cos(t2)*cos(t3)*sin(t1)) - sin(t1)*sin(t2)*sin(t4)) + sin(t5)*(cos(t1)*cos(t3) - cos(t2)*sin(t1)*sin(t3)));
                                                                                                                                                                                                                                                                                                                                                              1,                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                           cos(t2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       sin(t2)*sin(t3),                                                                                                                                         cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         sin(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) + cos(t5)*sin(t2)*sin(t3),                                                                                                       cos(t6)*(cos(t2)*cos(t4) - cos(t3)*sin(t2)*sin(t4)) - sin(t6)*(cos(t5)*(cos(t2)*sin(t4) + cos(t3)*cos(t4)*sin(t2)) - sin(t2)*sin(t3)*sin(t5))]





end

